= IoT-Spaß mit den Lolin-Boards

Auf den Lolin-Boards befindet sich ein ESP8266, ein sehr vielseitiges System-on-a-Chip, welches neben mehreren Ein-/Ausgängen auch WLAN on Board bietet. Daher eignen sie sich sehr gut für irgendwelche IoT-Experimente.

Die Lolin-Boards können (unter anderem) mit Hilfe der Arduino-IDE programmiert werden. Diese kann https://www.arduino.cc/en/Main/Software[hier heruntergeladen] werden.
Nach dem Start der IDE muss der Boardmanager für den ESP8266-Chip installiert werden. Hierzu muss in den Einstellungen der Arduino-IDE die URL des Boardmanagers eingegeben werden:
http://arduino.esp8266.com/stable/package_esp8266com_index.json
Wählt man nun das Board "NodeMCU 1.0", kann es auch schon losgehen!

Der USB-Anschluss bildet eine serielle Verbindung zum Lolin Developer Board. Je nach Windows-Version kann es sein, dass ein passender Treiber für den verwendeten CH341-Chip installiert werden muss; eine Treibersammlung findet man beispielsweise https://github.com/himalayanelixir/Arduino_USB_Drivers[hier] (ohne Gewähr bezüglich Viren oder ähnlichem ;-)

Schritt-für-Schritt-Anleitungen zur Einrichtung der IDE findet man im Internet zuhauf, beispielsweise:

* http://henrysbench.capnfatz.com/henrys-bench/arduino-projects-tips-and-more/arduino-esp8266-lolin-nodemcu-getting-started/
* http://www.instructables.com/id/Quick-Start-to-Nodemcu-ESP8266-on-Arduino-IDE/

== MQTT mit Homie

Schnell zu IoT-Ergebnissen kommt man mit der https://github.com/marvinroger/homie-esp8266[Bibliothek Homie]. Sie erledigt die MQTT-Kommunikation, ausserdem lassen sich hiermit die programmierten Boards einfach konfigurieren: Ist noch keine Konfiguration hinterlegt, erzeugt Homie beim ersten Start einen WLAN-Accesspoint und bietet über eine Webseite die Möglichkeit, Zugangsdaten für WLAN und den MQTT-Server zu hinterlegen. Auch eigene Parameter können hier eingestellt werden.

Zur Verwendung muss die Bibliothek (samt ihrer Abhängikeiten) zunächst aus den link:lib/[ZIP-Archiven] (Sketch - Include Library - Add .zip Library) installiert werden. Anschließend kann sie in eignen Programmen verwendet werden.

Die Beispielsanwendung kann nun übersetzt und übertragen werden. Mit Tools - Sketch Data Upload werden die Daten für die Konfigurationsseite übertragen. Und sollte etwas nicht gehen: Homie ist über die serielle Konsole sehr gesprächig und bietet auch eine API für eigene Lognachrichten.

Viel Spaß!
